# -
# Copyright (c) 2026 Florin Tanasă <florin.tanasa@gmail.com>
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# -

import csv
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

from jmix_cli.core.project import COMPANY, PROIECT_PATH, PROJECT, company_path, project_name
from jmix_cli.core.files import write_file, update_checkbox_required_state_property
from jmix_cli.core.logger import get_logger
from jmix_cli.exceptions import JmixCliError, ConfigurationError, GenerationError, UserInputError

logger = get_logger("jmix_cli.cli.dry_run")

DRY_RUN_SERVER_PORT = "0"


def _ensure_dry_run_server_port(properties_path: Path) -> None:
    if not properties_path.exists():
        return
    content = properties_path.read_text(encoding="utf-8")
    if "server.port=" in content:
        content = re.sub(r"server\.port\s*=\s*.*", f"server.port={DRY_RUN_SERVER_PORT}", content)
    else:
        content += f"\nserver.port={DRY_RUN_SERVER_PORT}\n"
    properties_path.write_text(content, encoding="utf-8")


def _copy_project_to_temp() -> Path:
    src = Path.cwd()
    temp_dir = Path(tempfile.mkdtemp(prefix="jmix-dry-run-"))
    logger.info(f"[dry-run] Creating temporary project at: {temp_dir}")

    dirs_to_copy = ["gradle"]
    files_to_copy = [
        "build.gradle",
        "settings.gradle",
        "gradle.properties",
        "gradlew",
        "gradlew.bat",
        "entities.csv",
        "relations.csv",
        "traits.csv",
        "roles.csv",
    ]

    for d in dirs_to_copy:
        s = src / d
        if s.exists():
            shutil.copytree(s, temp_dir / d)

    for f in files_to_copy:
        s = src / f
        if s.exists():
            shutil.copy2(s, temp_dir / f)

    src_dir = src / "src"
    temp_src = temp_dir / "src"
    if src_dir.exists():
        shutil.copytree(src_dir, temp_src)

        resources = temp_src / "main" / "resources"
        if resources.exists():
            for changelog_dir in resources.rglob("*/liquibase/changelog"):
                if not changelog_dir.is_dir():
                    continue
                for path in list(changelog_dir.iterdir()):
                    if path.is_file() and path.name != "010-init-user.xml":
                        path.unlink()
                    elif path.is_dir():
                        shutil.rmtree(path, ignore_errors=True)

    props = temp_dir / "src" / "main" / "resources" / "application.properties"
    _ensure_dry_run_server_port(props)

    readme = temp_dir / "README-dry-run.txt"
    readme.write_text(
        f"Dry-run output for project: {_read_project_name(temp_dir / 'settings.gradle')}\n"
        f"Generated by jmix-cli --dry-run\n\n"
        f"To run:\n"
        f"  cd {temp_dir}\n"
        f"  chmod +x gradlew\n"
        f"  ./gradlew bootRun\n\n"
        f"Note: server.port={DRY_RUN_SERVER_PORT} was set, so Tomcat will pick a random free port.\n"
        f"Look for 'Application started at http://localhost:XXXX' in the bootRun log.\n"
        f"To use a fixed port, edit src/main/resources/application.properties and set server.port=<desired_port>.\n",
        encoding="utf-8",
    )
    return temp_dir


def _read_project_name(settings_path: Path) -> str | None:
    if not settings_path.exists():
        return None
    text = settings_path.read_text(encoding="utf-8")
    m = re.search(r"""rootProject\.name\s*=\s*(['"])(.*?)\1""", text)
    return m.group(2) if m else None


def _read_company_name(build_path: Path) -> str | None:
    if not build_path.exists():
        return None
    text = build_path.read_text(encoding="utf-8")
    m = re.search(r"""group\s*=\s*(['"])(.*?)\1""", text)
    return m.group(2) if m else None


def _patch_globals_for_dry_run(temp_dir: Path) -> None:
    import sys
    import jmix_cli.core.project as core_project

    company = _read_company_name(temp_dir / "build.gradle") or ""
    project = _read_project_name(temp_dir / "settings.gradle") or ""
    project_name = project.lower()
    company_path = company.replace(".", "/") if company else ""

    new_values = {
        "PROIECT_PATH": temp_dir,
        "PROJECT": project,
        "project_name": project_name,
        "COMPANY": company,
        "company_path": company_path,
    }

    for name, value in new_values.items():
        if hasattr(core_project, name):
            setattr(core_project, name, value)

    for mod_name, mod in list(sys.modules.items()):
        if mod_name == "jmix_cli" or mod_name.startswith("jmix_cli."):
            for name, value in new_values.items():
                if name in mod.__dict__:
                    try:
                        mod.__dict__[name] = value
                    except Exception:
                        pass


def _print_dry_run_summary(temp_dir: Path, original_dir: Path) -> None:
    java_files = list(temp_dir.rglob("*.java"))
    xml_files = list(temp_dir.rglob("*.xml"))
    props_files = list(temp_dir.rglob("*.properties"))

    logger.info("=" * 70)
    logger.info("[dry-run] Generation completed successfully!")
    logger.info("=" * 70)
    logger.info(f"  Dry-run output directory: {temp_dir}")
    logger.info(f"  Generated Java files:     {len(java_files)}")
    logger.info(f"  Generated XML files:      {len(xml_files)}")
    logger.info(f"  Generated properties:     {len(props_files)}")
    logger.info("\n  To inspect differences:")
    logger.info(f"    meld {original_dir} {temp_dir}")
    logger.info("\n  To run the application:")
    logger.info(f"    cd {temp_dir} && ./gradlew bootRun")
    logger.info("=" * 70 + "\n")


def _dry_run_enabled() -> bool:
    return "--dry-run" in sys.argv


def _finish_dry_run(temp_dir: Path | None, original_dir: Path | None = None) -> None:
    if temp_dir is not None and original_dir is not None:
        _print_dry_run_summary(temp_dir, original_dir)
    elif temp_dir is not None:
        _print_dry_run_summary(temp_dir, temp_dir)


def _handle_error(error: Exception) -> None:
    if isinstance(error, UserInputError):
        logger.error(f"[-] {error}")
    elif isinstance(error, ConfigurationError):
        logger.error(f"[-] Configuration error: {error}")
    elif isinstance(error, GenerationError):
        logger.error(f"[-] Generation error: {error}")
    elif isinstance(error, JmixCliError):
        logger.error(f"[-] {error}")
    else:
        logger.error(f"[-] Unexpected error: {error}")
    sys.exit(1)


def inject_audit_dependencies() -> None:
    from jmix_cli.core.project import PROIECT_PATH, company_path, project_name

    build_gradle_path = PROIECT_PATH / "build.gradle"
    if build_gradle_path.exists():
        traits_path = Path("traits.csv")
        if traits_path.exists():
            audit_needed = False
            with traits_path.open(encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    if (
                        row.get("audit_of_creation", "").strip().lower() == "true"
                        or row.get("audit_of_modification", "").strip().lower() == "true"
                    ):
                        audit_needed = True
                        break

            if audit_needed:
                content = build_gradle_path.read_text(encoding="utf-8")
                has_starter = "jmix-audit-starter" in content
                has_flowui = "jmix-audit-flowui-starter" in content
                if not has_starter or not has_flowui:
                    lines_to_add = []
                    if not has_starter:
                        lines_to_add.append("    implementation 'io.jmix.audit:jmix-audit-starter' // Automatically configured via Jmix CLI")
                    if not has_flowui:
                        lines_to_add.append("    implementation 'io.jmix.audit:jmix-audit-flowui-starter' // Automatically configured via Jmix CLI")
                    if lines_to_add and "dependencies {" in content:
                        insertion = "\n".join([""] + lines_to_add) + "\n"
                        content = content.replace("dependencies {", f"dependencies {{{insertion}", 1)
                        build_gradle_path.write_text(content, encoding="utf-8")
                        logger.info("[+] Injected Jmix Audit dependencies into build.gradle")

    changelog_path = PROIECT_PATH / "src" / "main" / "resources" / company_path / project_name / "liquibase" / "changelog.xml"
    if changelog_path.exists():
        changelog_content = changelog_path.read_text(encoding="utf-8")
        if "/io/jmix/audit/liquibase/changelog.xml" not in changelog_content:
            insert_marker = f'    <includeAll path="/{company_path}/{project_name}/liquibase/changelog"/>'
            if insert_marker in changelog_content:
                audit_include = '    <include file="/io/jmix/audit/liquibase/changelog.xml"/>\n'
                changelog_content = changelog_content.replace(insert_marker, f"{audit_include}{insert_marker}")
                changelog_path.write_text(changelog_content, encoding="utf-8")
                logger.info("[+] Injected Jmix Audit changelog into liquibase/changelog.xml")


def _finalize_composition_relationships() -> None:
    from pathlib import Path
    import csv
    from datetime import datetime
    from jmix_cli.core.project import PROIECT_PATH, company_path, project_name
    from jmix_cli.core.files import write_file
    from jmix_cli.core.java import inject_import_if_missing
    from jmix_cli.entity import get_relations_from_csv

    logger.info("\n[⚡] PHASE 1.5: Finalizing Composition relationships...")
    relations_path = Path("relations.csv")
    if not relations_path.exists():
        return
    from jmix_cli.core.csv import validate_csv_path
    validate_csv_path("relations.csv", ["source_entity", "relation_type", "target_entity", "field_name", "mandatory"])
    with relations_path.open(encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            r_type = row["relation_type"].strip()
            if r_type != "COMPOSITION_1:1":
                continue
            src_class = row["source_entity"].strip()
            tgt_class = row["target_entity"].strip()
            f_name = row["field_name"].strip()
            src_file_path = Path("src") / "main" / "java" / company_path / project_name / "entity" / f"{src_class}.java"
            tgt_file_path = Path("src") / "main" / "java" / company_path / project_name / "entity" / f"{tgt_class}.java"
            if not src_file_path.exists() or not tgt_file_path.exists():
                continue
            src_content = src_file_path.read_text(encoding="utf-8")
            if f"private {tgt_class} {f_name};" not in src_content:
                logger.info(f" 🔗 Finalizing @Composition 1:1 in {src_class}")
                sql_fk_col = f"{f_name.upper()}_ID"
                mandatory_val = row.get("mandatory", "false").strip().lower() == "true"
                join_col_attr = f'@JoinColumn(name = "{sql_fk_col}", nullable = false)' if mandatory_val else f'@JoinColumn(name = "{sql_fk_col}")'
                not_null_anno = "    @NotNull\n" if mandatory_val else ""
                comp_field = f'    @Composition\n    @OnDelete(DeletePolicy.CASCADE)\n    {join_col_attr}\n{not_null_anno}    @OneToOne(fetch = FetchType.LAZY)\n    private {tgt_class} {f_name};\n\n'
                comp_caps = f_name[0].upper() + f_name[1:]
                comp_methods = f"    public {tgt_class} get{comp_caps}() {{\n        return {f_name};\n    }}\n\n"
                comp_methods += f"    public void set{comp_caps}({tgt_class} {f_name}) {{\n        this.{f_name} = {f_name};\n    }}\n\n"
                src_content = inject_import_if_missing(src_content, "io.jmix.core.metamodel.annotation.Composition")
                src_content = inject_import_if_missing(src_content, "io.jmix.core.entity.annotation.OnDelete")
                src_content = inject_import_if_missing(src_content, "io.jmix.core.DeletePolicy")
                src_content = inject_import_if_missing(src_content, "jakarta.persistence.OneToOne")
                src_content = inject_import_if_missing(src_content, "jakarta.persistence.JoinColumn")
                src_content = inject_import_if_missing(src_content, "jakarta.persistence.FetchType")
                if mandatory_val:
                    src_content = inject_import_if_missing(src_content, "jakarta.validation.constraints.NotNull")
                if "    public UUID getId()" in src_content:
                    src_content = src_content.replace(
                        "    public UUID getId()",
                        f"{comp_field}    public UUID getId()",
                    )
                last_brace = src_content.rfind("}")
                if last_brace != -1:
                    src_content = (
                        src_content[:last_brace]
                        + "\n"
                        + comp_methods
                        + src_content[last_brace:]
                    )
                src_file_path.write_text(src_content, encoding="utf-8")

            tgt_content = tgt_file_path.read_text(encoding="utf-8")
            inv_field_name = src_class[0].lower() + src_class[1:]
            if f"private {src_class} {inv_field_name};" not in tgt_content:
                logger.info(f" 🔗 Finalizing inverse 1:1 in {tgt_class}")
                inv_field = f'    @OneToOne(fetch = FetchType.LAZY, mappedBy = "{f_name}")\n    private {src_class} {inv_field_name};\n\n'
                inv_caps = inv_field_name[0].upper() + inv_field_name[1:]
                inv_methods = f"    public {src_class} get{inv_caps}() {{\n        return {inv_field_name};\n    }}\n\n"
                inv_methods += f"    public void set{inv_caps}({src_class} {inv_field_name}) {{\n        this.{inv_field_name} = {inv_field_name};\n    }}\n\n"
                tgt_content = inject_import_if_missing(tgt_content, "jakarta.persistence.OneToOne")
                tgt_content = inject_import_if_missing(tgt_content, "jakarta.persistence.FetchType")
                if "    public UUID getId()" in tgt_content:
                    tgt_content = tgt_content.replace(
                        "    public UUID getId()",
                        f"{inv_field}    public UUID getId()",
                    )
                last_brace = tgt_content.rfind("}")
                if last_brace != -1:
                    tgt_content = (
                        tgt_content[:last_brace]
                        + "\n"
                        + inv_methods
                        + tgt_content[last_brace:]
                    )
                tgt_file_path.write_text(tgt_content, encoding="utf-8")

    logger.info("\n✅ Entity generation completed!")
