# -
# Copyright (c) 2026 Florin Tanasă <florin.tanasa@gmail.com>
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# -

"""Integration tests for jmix-cli end-to-end commands."""

import os
import subprocess
import tempfile
from pathlib import Path


class TestBuildAllIntegration:
    """Integration tests for build-all command."""

    def test_build_all_generates_entities(self, tmp_path: Path):
        """Test that build-all generates entity classes from CSV."""
        os.chdir(tmp_path)

        # Initialize project
        result = subprocess.run(
            ["python3", "/home/florin/git/jmix-cli/jmix-cli.py", "init", "testproj", "com.company", "ro"],
            capture_output=True,
            text=True,
            cwd=tmp_path,
        )
        assert result.returncode == 0, f"Init failed: {result.stderr}"

        # Create CSV files in project root with custom entity
        (tmp_path / "testproj" / "entities.csv").write_text(
            "entity_name,field_name,field_type,mandatory,unique\n"
            "User,name,String,true,false\n"
            "User,email,String,true,true\n"
            "CustomEntity,title,String,true,false\n"
        )

        (tmp_path / "testproj" / "relations.csv").write_text(
            "source_entity,relation_type,target_entity,field_name,mandatory\n"
        )

        (tmp_path / "testproj" / "roles.csv").write_text(
            "name,code,entity_name,ui_list,ui_detail,create,read,update,delete\n"
            "Admin,admin,User,true,true,true,true,true,true\n"
        )

        (tmp_path / "testproj" / "traits.csv").write_text(
            "entity_name,versioned,audit_of_creation,audit_of_modification,soft_delete\n"
            "User,false,false,false,false\n"
        )

        # Run build-all
        result = subprocess.run(
            ["python3", "/home/florin/git/jmix-cli/jmix-cli.py", "build-all"],
            capture_output=True,
            text=True,
            cwd=tmp_path / "testproj",
        )
        assert result.returncode == 0, f"Build-all failed: {result.stderr}"

        # Check that entity files were generated by checking Java files exist
        user_entity = tmp_path / "testproj" / "src" / "main" / "java" / "com" / "company" / "testproj" / "entity" / "User.java"
        custom_entity = tmp_path / "testproj" / "src" / "main" / "java" / "com" / "company" / "testproj" / "entity" / "CustomEntity.java"

        assert user_entity.exists(), "User.java not generated"
        assert custom_entity.exists(), "CustomEntity.java not generated"

        # Check that User has the email field from CSV (not name, since User already exists)
        user_content = user_entity.read_text()
        assert "private String email;" in user_content

        custom_content = custom_entity.read_text()
        assert "private String title;" in custom_content

    def test_build_all_generates_security(self, tmp_path: Path):
        """Test that build-all generates security roles."""
        os.chdir(tmp_path)

        result = subprocess.run(
            ["python3", "/home/florin/git/jmix-cli/jmix-cli.py", "init", "testproj", "com.company", "ro"],
            capture_output=True,
            text=True,
            cwd=tmp_path,
        )
        assert result.returncode == 0

        (tmp_path / "testproj" / "entities.csv").write_text(
            "entity_name,field_name,field_type,mandatory,unique\n"
            "User,name,String,true,false\n"
        )

        (tmp_path / "testproj" / "relations.csv").write_text(
            "source_entity,relation_type,target_entity,field_name,mandatory\n"
        )

        (tmp_path / "testproj" / "roles.csv").write_text(
            "name,code,entity_name,ui_list,ui_detail,create,read,update,delete\n"
            "Admin,admin,User,true,true,true,true,true,true\n"
        )

        result = subprocess.run(
            ["python3", "/home/florin/git/jmix-cli/jmix-cli.py", "build-all"],
            capture_output=True,
            text=True,
            cwd=tmp_path / "testproj",
        )
        assert result.returncode == 0

        # Check that security files were generated
        admin_role = tmp_path / "testproj" / "src" / "main" / "java" / "com" / "company" / "testproj" / "security" / "AdminRole.java"
        assert admin_role.exists(), "AdminRole.java not generated"
